# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0949b52a3f721b3fed2fbe7aa8c44a7547a19863a28a6aad65ea54414c555cd077468eb0298d5b92ba403ca3d5a0f0ed10e0b2b6753597eb04a5786e6c66b05a

test:
  secret_key_base: 813883edd7ac9727c6a725a27265e19e9002465f092132b369c8a34ab0a8291ed94046af803e98068bb0d8a5cfcacff13e49c3f0bf261a5deb254c6569735ba8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
